// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/chat/:userId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/[userId].get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/[userId].post').default>>>>
    }
    '/api/chat': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/index.get').default>>>>
    }
    '/api/collection/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collection/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collection/[id].patch').default>>>>
    }
    '/api/collection': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collection/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collection/index.post').default>>>>
    }
    '/api/meta': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/meta.get').default>>>>
    }
    '/api/pet-images/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pet-images/[id].delete').default>>>>
    }
    '/api/pet-images': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pet-images/index.post').default>>>>
    }
    '/api/pets/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pets/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pets/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pets/[id].patch').default>>>>
    }
    '/api/pets/:id/owners': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pets/[id]/owners.get').default>>>>
    }
    '/api/pets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pets/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pets/index.post').default>>>>
    }
    '/api/trades/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trades/[id].patch').default>>>>
    }
    '/api/trades': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trades/index.post').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].patch').default>>>>
    }
    '/api/users/:id/ban': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/ban.patch').default>>>>
    }
    '/api/users/:id/collection': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/collection.get').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
    }
    '/api/users/me': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/me.patch').default>>>>
    }
    '/api/wishlist/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/[id].delete').default>>>>
    }
    '/api/wishlist': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wishlist/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}